# Generated by Django 5.1.3 on 2024-11-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("nombre",),
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
    ]
