# Generated by Django 5.1.3 on 2024-11-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("nombre",),
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
            },
        ),
    ]
