# Generated by Django 5.1.3 on 2024-11-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_braintree_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="last_name", new_name="apellidos",
        ),
        migrations.RenameField(model_name="order", old_name="city", new_name="ciudad",),
        migrations.RenameField(
            model_name="order", old_name="postal_code", new_name="código_postal",
        ),
        migrations.RenameField(
            model_name="order", old_name="address", new_name="dirección",
        ),
        migrations.RenameField(
            model_name="order", old_name="first_name", new_name="nombre",
        ),
    ]
