# Generated by Django 5.1.3 on 2024-11-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_last_name_order_apellidos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="order", options={"ordering": ("-creado",)},),
        migrations.RenameField(
            model_name="order", old_name="updated", new_name="actualizado",
        ),
        migrations.RenameField(
            model_name="order", old_name="created", new_name="creado",
        ),
        migrations.RenameField(model_name="order", old_name="paid", new_name="pagado",),
    ]
