# Generated by Django 5.1.3 on 2024-11-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0004_alter_order_options_rename_updated_order_actualizado_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-creado",),
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "artículo pedido",
                "verbose_name_plural": "artículos pedido",
            },
        ),
        migrations.RenameField(
            model_name="orderitem", old_name="quantity", new_name="cantidad",
        ),
        migrations.RenameField(
            model_name="orderitem", old_name="price", new_name="precio",
        ),
        migrations.RenameField(
            model_name="orderitem", old_name="product", new_name="producto",
        ),
    ]
