# Generated by Django 5.1.3 on 2024-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="entrega_en_oficina_de_correos",
            field=models.BooleanField(default=False),
        ),
    ]
