# Generated by Django 5.1.3 on 2024-11-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_fecha_salida_almacen_order_notas_seguimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="codigo_unico",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
